<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudyPlanner.Data\StudyPlanner.Data.csproj" />
    <ProjectReference Include="..\StudyPlanner.GCommon\StudyPlanner.GCommon.csproj" />
  </ItemGroup>

</Project>
