<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudyPlanner.Data\StudyPlanner.Data.csproj" />
    <ProjectReference Include="..\StudyPlanner.ViewModels\StudyPlanner.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2024.12.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Category\" />
  </ItemGroup>

</Project>
